### ISSUE TITLE
Suggestion: adopt ДСТУ 9112:2021

### ISSUE THREAD

**Issue by paiv** [jkramr/latynka#8]
Reasons to adopt:
- It's a standard, there will be no other to replace it. Personal latynka projects will fade away.
- It defines forward and backward transliteration, and will help in resolving issues like #3

**Comment by jkramr** [comment]
Described issue and ДСТУ 9112:2021 is not related to the alphabet implemented in this project. please watch the video and README.MD.
GitHub issues are also not the best place for discussing the overall relevance of the project or the adoption plan of the alphabet.
Neither am I (or Maksym) the person of expertise or power to implement such adoption.

**Comment by paiv** [comment]
@jkramr It was a suggestion. It seemed to me that neither of you was aware of ДСТУ 9112:2021 since it was never mentioned nor critiqued. Your project (and the "alphabet") is an attempt to provide an alternative to the exact thing the standard has specified. Therefore I'd consider your efforts futile and destructive since it further fragments community by swaying adopters to non-standard transliteration.

**Comment by jkramr** [comment]
I'll have to repeat myself: it does not have anything to do with standard transliteration or it's adoption.

**Comment by paiv** [comment]
> I'll have to repeat myself: it does not have anything to do with standard transliteration or it's adoption.

Well, your statement is provably false. I'm open for discussion on any platform.

**Comment by jkramr** [comment]
This project does not have anything to do with transliteration. Transliteration has specific goals: take existing language alphabet (be it cyrillic, chinese characters etc.) and transliterate it in a way that is more readable for those unfamiliar with the scrypt aka - foreigners, not native speakers. 

This project has different goals entirely. When using latin script INSTEAD of cyrillic, the starting point is 

1) taking language phonetics
2) trying to map them with latin characters in a way that's readable by >>>native Ukrainain speakers<<<, mind you - not foreigners trying to read cyrillic.
3) applying the spelling rules that has >>>Ukrainian<<< phonetics in mind, not English, Polish or whoever is intended reader in case of transliteration

Although easier readability for foreigners it is indeed a side-effect of latin scrypt, it's not a rule-defining goal. It is not a subtle but a crucial distinction to transliteration.

If you think you found a bug (e.g. the algorithm does not work as described in the rules in README and/or the video) - feel free to post it here.

If you're asking to change the rules of the alphabet - that is not a concern for this particular library and I'm not the author of the rules either. 

If you have any particular ideas - feel free to fork this repo or make your own from scratch according to your needs/goals.

I'm NOT open for a discussion about general relevance of the project I do for fun and in my personal time. I am specifically not open for discussion around points like "what you're doing is futile" when it comes to my pet projects :).
Especially not in GitHub issues.

I'll leave it at that.
